name: Python app

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/devcontainer
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        
      - name: Run pytest
        run: pytest .